on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      ['main']
env:
  XML_SCHEMA: "plugins.xsd"

name:  plugin-gallery
jobs:
  plugin-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "install Dependencies"
        run: | 
          sudo apt-get update -qq
          sudo apt-get install libxml2-utils
          npm install -g pkp-plugin-cli
        shell: bash

      - name: Install  for push
        if: ${{  github.event_name  == 'push'}}
        run: |
          git clone -b ${{ github.head_ref || github.ref_name }} https://github.com/${{ github.repository}} ~/${{ github.event.repository.name }}  --depth 5
        shell: bash

      - name: Install for pull_request
        if: ${{github.event_name  == 'pull_request'}}
        run: |
          git clone -b ${{ github.event.pull_request.head.ref}} ${{ github.event.pull_request.head.repo.html_url}} ~/${{ github.event.pull_request.head.repo.name }} --depth 5
        shell: bash

      - name: "Run plugin validation"
        run: |
          cd ~/${{github.event.pull_request.head.repo.name || github.event.repository.name  }}
          xmllint --schema ./plugins.xsd ./plugins.xml --noout
        shell: bash

      - name:  For push
        if: ${{  github.event_name  == 'push'    && github.head_ref == 'main'}}
        run: |
          cd ~/${{github.event.pull_request.head.repo.name || github.event.repository.name  }}
          pkp-plugin validate-all-releases --input ./plugins.xml
        shell: bash

      - name: For pull request
        if: ${{  github.event_name  == 'pull_request'}}
        run: |
          cd ~/${{github.event.pull_request.head.repo.name || github.event.repository.name  }}
          pwd
          pkp-plugin validate-new-release
        shell: bash

      - name: For push
        if: ${{  github.event_name  == 'push'    && github.head_ref == 'main'}}
        run: |
          cd ~/${{github.event.pull_request.head.repo.name || github.event.repository.name  }}
          GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} pkp-plugin generate-site $TRAVIS_BUILD_DIR/plugins.xml
        shell: bash